name: test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['tip', '1.22', '1.21', '1.20', '1.19', '1.18', '1.17', '1.16']
    steps:
      - name: Setup Go
        if: matrix.go-version != 'tip'
        uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup Go tip if needed
        if: matrix.go-version == 'tip'
        run: |
          set -ex
          commit=$(git ls-remote https://github.com/golang/go.git HEAD | awk '{print $1}')
          curl -LOJ https://storage.googleapis.com/go-build-snap/go/linux-amd64/${commit}.tar.gz
          rm -rf /usr/local/go
          sudo tar xzf ${commit}.tar.gz -C /usr/local
          sudo ln -sf /usr/local/go/bin/go /usr/bin/go
          go version
      - uses: actions/checkout@v4
      - name: Build
        run: go build -v -race
      - name: Test
        run: go test -v
      - name: Bench
        run: go test -v -run=none -bench=.
